version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=thegogashvili
      - POSTGRES_PASSWORD=giga
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
