version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=giga
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  api:
    build: .
    env_file:
      - './.env'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis-data:
    driver: local
